[package]
name = "nonogram-rs"
version = "0.1.0"
authors = ["Quentin Michel <quentinmichel69110@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
termion = "*"
lazy_static = "1.3.0"
failure = "0.1.5"
